version: '3.3'
services:
  spark-master:
    image: thiagolange/cluster-spark:latest
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    container_name: spark-master
    ports:
      - "8080:8080"
    command: bash -c "/opt/spark/sbin/start-master.sh && tail -f /dev/null"

  spark-worker-1:
    image: thiagolange/cluster-spark:latest
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    container_name: spark-worker-1
    command: bash -c "/opt/spark/sbin/start-worker.sh spark://spark-master:7077 && tail -f /dev/null"
    depends_on:
      - spark-master

  spark-worker-2:
    image: thiagolange/cluster-spark:latest
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    container_name: spark-worker-2
    command: bash -c "/opt/spark/sbin/start-worker.sh spark://spark-master:7077 && tail -f /dev/null"
    depends_on:
      - spark-master
